version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: ghostpin-postgres
    environment:
      POSTGRES_DB: ghostpin
      POSTGRES_USER: danny
      POSTGRES_PASSWORD: 2024@Paris!
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ghostpin -d ghostpin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    container_name: ghostpin-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
